// Code generated by parsley-cli; DO NOT EDIT.
//
// This file was automatically generated and any changes to it will be overwritten.
// To extend or modify the behavior of this code, implement the MethodInterceptor interface and provide your custom logic there.

package internal

import (
	"fmt"

	"github.com/matzefriedrich/parsley/pkg/features"
)

// greeterProxyImpl A generated proxy service type for Greeter objects.
type greeterProxyImpl struct {
	features.ProxyBase
	target Greeter
}

// GreeterProxy An interface type for Greeter objects. Parsley needs this to distinguish the proxy from the actual implementation.
type GreeterProxy interface {
	Greeter
}

// NewGreeterProxyImpl Creates a new GreeterProxy object. Register this constructor method with the registry.
func NewGreeterProxyImpl(target Greeter, interceptors []features.MethodInterceptor) GreeterProxy {
	return &greeterProxyImpl{
		ProxyBase: features.NewProxyBase(target, interceptors),
		target:    target,
	}
}

func (p *greeterProxyImpl) SayHello(name string, polite bool) {

	const methodName = "SayHello"
	parameters := map[string]interface{}{
		"name":   name,
		"polite": polite,
	}

	parameterNames := []string{"name", "polite"}
	resultNames := []string{}

	callContext := features.NewMethodCallContext(methodName, parameterNames, parameters, resultNames...)
	p.InvokeEnterMethodInterceptors(callContext)
	defer func() {
		p.InvokeExitMethodInterceptors(callContext)
	}()

	p.target.SayHello(name, polite)
}

var _ Greeter = &greeterProxyImpl{}
